/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "unit.check" instead.
 */

#include <check.h>

#line 1 "unit.check"
#include <stdio.h>
#include <string.h>

#include "s21_string.h"

START_TEST(s21_strlen_test) {
    char *str = "hello world";
    char *src = " ";
    ck_assert_int_eq(strlen(str), s21_strlen(str));
    ck_assert_int_eq(strlen(" "), s21_strlen(" "));
    ck_assert_int_eq(strlen(""), s21_strlen(""));
}
END_TEST

START_TEST(s21_memcmp_test) {
    ck_assert_int_eq(memcmp("", " ", 5), s21_memcmp("", " ", 5));
    ck_assert_int_eq(memcmp("hello world", " ", -1),
                     s21_memcmp("hello world", " ", -1));
    ck_assert_int_eq(memcmp("hello world", " ", 5),
                     s21_memcmp("hello world", " ", 5));
}
END_TEST

START_TEST(s21_strcmp_test) {
    char *str = "hello world";
    char *src = " ";
    ck_assert_int_eq(strcmp(src, str), s21_strcmp(src, str));
    // ck_assert_int_eq(strcmp(" ", ""), s21_strcmp(" ", ""));
    ck_assert_int_eq(strcmp("", ""), s21_strcmp("", ""));
}
END_TEST

START_TEST(s21_strncmp_test) {
    char *str = "hello world";
    char *src = " ";
    char s1[20] = "hello";
    char s2[20] = "";
    ck_assert_int_eq(strncmp(src, str, 5), s21_strncmp(src, str, 5));
    ck_assert_int_eq(strncmp(s1, s2, 3), s21_strncmp(s1, s2, 3));
    ck_assert_int_eq(strncmp("", "", -3), s21_strncmp("", "", -3));
}
END_TEST

START_TEST(s21_s21_strcspn_test) {
    char *str = "hello world";
    char *src = " ";
    char s1[20] = "hello";
    char s2[20] = "";
    ck_assert_uint_eq(strcspn(str, src), s21_strcspn(str, src));
    ck_assert_uint_eq(strcspn(s1, s2), s21_strcspn(s1, s2));
    ck_assert_uint_eq(strcspn("", ""), s21_strcspn("", ""));
}
END_TEST

START_TEST(s21_strchr_test) {
    char *str = "hello world";
    char *src = " ";
    ck_assert_pstr_eq(strchr(str, 32), s21_strchr(str, 32));
    ck_assert_pstr_eq(strchr(src, -0), s21_strchr(src, -0));
    ck_assert_pstr_eq(strchr("", 0), s21_strchr("", 0));
}
END_TEST

START_TEST(s21_strpbrk_test) {
    char *str = "hello world";
    char *src = " ";
    char s1[20] = "hello";
    char s2[20] = "";
    ck_assert_pstr_eq(strpbrk(src, str), s21_strpbrk(src, str));
    ck_assert_pstr_eq(strpbrk(s1, s2), s21_strpbrk(s1, s2));
    ck_assert_pstr_eq(strpbrk(" ", " "), s21_strpbrk(" ", " "));
}
END_TEST

START_TEST(s21_strrchr_test) {
    char *str = "hello world";
    char s1[20] = "hello";
    ck_assert_pstr_eq(strrchr(str, 32), s21_strrchr(str, 32));
    ck_assert_pstr_eq(strrchr(s1, 0), s21_strrchr(s1, 0));
    ck_assert_pstr_eq(strrchr(" ", 32), s21_strrchr(" ", 32));
}
END_TEST

START_TEST(s21_strstr_test) {
    char s1[20] = "hello";
    ck_assert_pstr_eq(strstr(s1, ""), s21_strstr(s1, ""));
    ck_assert_pstr_eq(strstr("123456789", "234"),
                      s21_strstr("123456789", "234"));
}
END_TEST

START_TEST(s21_strtok_test) {
    char *str = "hello world";
    ck_assert_pstr_eq(strtok(str, ""), s21_strtok(str, ""));
    ck_assert_pstr_eq(strtok(str, "123"), s21_strtok(str, "123"));
    ck_assert_pstr_eq(strtok("", ""), s21_strtok("", ""));
}
END_TEST

START_TEST(s21_strcat_test) {
    char s1[20] = "hello";
    char s2[20] = "";
    ck_assert_pstr_eq(strcat(s1, s2), s21_strcat(s1, s2));
    ck_assert_pstr_eq(strcat(s1, s2), s21_strcat(s1, s2));
    // ck_assert_pstr_eq(strcat(s1, s2), s21_strcat(s1, s2));
}
END_TEST

START_TEST(s21_strncat_test) {
    char s1[20] = "hello";
    char s2[20] = "";
    ck_assert_pstr_eq(strncat(s1, s2, 3), s21_strncat(s1, s2, 3));
    ck_assert_pstr_eq(strncat(s1, s2, 0), s21_strncat(s1, s2, 0));
    // ck_assert_pstr_eq(strncat("", "", 0), s21_strncat("", "", 0));
}
END_TEST

START_TEST(s21_strerror_test) {
    for (int i = 0; i < 150; i++) {
        ck_assert_pstr_eq(strerror(i), s21_strerror(i));
    }
}
END_TEST

START_TEST(s21_strcpy_test) {
    char s1[20] = "hello";
    char s2[20] = "";
    ck_assert_pstr_eq(strcpy(s1, s2), s21_strcpy(s1, s2));
}
END_TEST

START_TEST(s21_strncpy_test) {
    char s1[20] = "hello";
    char s2[20] = "";
    ck_assert_pstr_eq(strncpy(s1, s2, 2), s21_strncpy(s1, s2, 2));
}
END_TEST

START_TEST(s21_strspn_test) {
    char *str = "hello world";
    char *src = " ";
    char s1[20] = "hello";
    char s2[20] = "";
    ck_assert_uint_eq(strspn(s1, "hello"), s21_strspn(s1, "hello"));
}
END_TEST

START_TEST(s21_memchr_test) {
    char *str = "hello world";
    ck_assert_ptr_eq(memchr(str, 'h', 32), s21_memchr(str, 'h', 32));
}
END_TEST

START_TEST(s21_memcpy_test) {
    char s1[20] = "hello";
    ck_assert_ptr_eq(memcpy(s1, "hello", 6), s21_memcpy(s1, "hello", 6));
}
END_TEST

START_TEST(s21_memmove_test) {
    char s1[20] = "hello";
    ck_assert_ptr_eq(memmove(s1, "hello", 6), s21_memmove(s1, "hello", 6));
}
END_TEST

START_TEST(s21_memset_test) {
    char s1[20] = "hello";
    ck_assert_ptr_eq(memset(s1, 'l', 5), s21_memset(s1, 'l', 5));
}
END_TEST

START_TEST(s21_to_upper_test) {
    char *str = "hello world";
    char *src = "123456789h";
    char *a = s21_to_upper(src);
    ck_assert_pstr_eq("123456789H", s21_to_upper(src));
    free(a);
}
END_TEST

START_TEST(s21_to_lower_test) {
    char *str = "hello world";
    char *src = "123456789H";
    char *a = s21_to_upper(src);
    ck_assert_pstr_eq("123456789h", s21_to_lower(src));
    free(a);
}
END_TEST

START_TEST(s21_to_insert_test) {
    char *str = "hello world";
    char *src = " ,Ai!";
    char *a = s21_insert(str, src, 11);
    ck_assert_pstr_eq("hello world ,Ai!", a);
    free(a);
}
END_TEST

// START_TEST(s21_to_trim_test) {
char *str = "hello world";
char *src = "hd";
// char *a = s21_trim("hello world", "hd");
// ck_assert_pstr_eq("ello world", a);
// free(a);
// }
// END_TEST

START_TEST(s21_sprintf_test) {
    char s1[20] = "hello";
    char s2[20] = "";
    char x[200];
    ck_assert_int_eq(sprintf(x, s1, s2), s21_sprintf(x, s1, s2));
    ck_assert_int_eq(sprintf(x, "hello %.6d", -123),
                     s21_sprintf(x, "hello %.6d", -123));
    ck_assert_int_eq(sprintf(x, "hello %-+4.5hd", -123),
                     s21_sprintf(x, "hello %-+4.5hd", -123));
    ck_assert_int_eq(sprintf(x, "hello % -.2ld", -123),
                     s21_sprintf(x, "hello % -.2ld", -123));
    ck_assert_int_eq(sprintf(x, "hello %-4.2ld", 123),
                     s21_sprintf(x, "hello %-4.2ld", 123));
    ck_assert_int_eq(sprintf(x, "hello %+hd", 123),
                     s21_sprintf(x, "hello %+hd", 123));
    ck_assert_int_eq(sprintf(x, "hello % d", 123),
                     s21_sprintf(x, "hello % d", 123));
    ck_assert_int_eq(sprintf(x, "123%%"), s21_sprintf(x, "123%%"));
    ck_assert_int_eq(sprintf(x, "123%c", 'f'), s21_sprintf(x, "123%c", 'f'));
    ck_assert_int_eq(sprintf(x, "123%-lc", 'f'),
                     s21_sprintf(x, "123%-lc", 'f'));
    ck_assert_int_eq(sprintf(x, "123%+c", 'f'), s21_sprintf(x, "123%+c", 'f'));
    ck_assert_int_eq(sprintf(x, "123% c", 'f'), s21_sprintf(x, "123% c", 'f'));
    ck_assert_int_eq(sprintf(x, "123%s", "asd"),
                     s21_sprintf(x, "123%s", "asd"));
    ck_assert_int_eq(sprintf(x, "123%s", ""), s21_sprintf(x, "123%s", ""));
    ck_assert_int_eq(sprintf(x, " "), s21_sprintf(x, " "));
    ck_assert_int_eq(sprintf(x, "123%-4s", "asd"),
                     s21_sprintf(x, "123%-4s", "asd"));
    ck_assert_int_eq(sprintf(x, "123%u", 12345678),
                     s21_sprintf(x, "123%u", 12345678));
    ck_assert_int_eq(sprintf(x, "123%-u", 12345678),
                     s21_sprintf(x, "123%-u", 12345678));
    ck_assert_int_eq(sprintf(x, "123%u", 12345678),
                     s21_sprintf(x, "123%u", 12345678));
    ck_assert_int_eq(sprintf(x, "123%4.2u", 12345678),
                     s21_sprintf(x, "123%4.2u", 12345678));
    ck_assert_int_eq(sprintf(x, "123%i", 12345678),
                     s21_sprintf(x, "123%i", 12345678));
    ck_assert_int_eq(sprintf(x, "123%-i", 12345678),
                     s21_sprintf(x, "123%-i", 12345678));
    ck_assert_int_eq(sprintf(x, "123%+i", 12345678),
                     s21_sprintf(x, "123%+i", 12345678));
    ck_assert_int_eq(sprintf(x, "123% i", 12345678),
                     s21_sprintf(x, "123% i", 12345678));
    ck_assert_int_eq(sprintf(x, "123% i 123 %-hd %s", 123, 123, "qwe"),
                     s21_sprintf(x, "123% i 123 %-hd %s", 123, 123, "qwe"));
    ck_assert_int_eq(sprintf(x, "123%f", 12.333333330),
                     s21_sprintf(x, "123%f", 12.333333330));
    ck_assert_int_eq(sprintf(x, "123%-4.2hf", 12.333333330),
                     s21_sprintf(x, "123%-4.2hf", 12.333333330));
    ck_assert_int_eq(sprintf(x, "123%+4.2lf", -12.333333330),
                     s21_sprintf(x, "123%+4.2lf", -12.333333330));
    ck_assert_int_eq(sprintf(x, "123% -f", 12.333333330),
                     s21_sprintf(x, "123% -f", 12.333333330));
}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_strlen_test);
    tcase_add_test(tc1_1, s21_memcmp_test);
    tcase_add_test(tc1_1, s21_strcmp_test);
    tcase_add_test(tc1_1, s21_strncmp_test);
    tcase_add_test(tc1_1, s21_s21_strcspn_test);
    tcase_add_test(tc1_1, s21_strchr_test);
    tcase_add_test(tc1_1, s21_strpbrk_test);
    tcase_add_test(tc1_1, s21_strrchr_test);
    tcase_add_test(tc1_1, s21_strstr_test);
    tcase_add_test(tc1_1, s21_strtok_test);
    tcase_add_test(tc1_1, s21_strcat_test);
    tcase_add_test(tc1_1, s21_strncat_test);
    tcase_add_test(tc1_1, s21_strerror_test);
    tcase_add_test(tc1_1, s21_strcpy_test);
    tcase_add_test(tc1_1, s21_strncpy_test);
    tcase_add_test(tc1_1, s21_strspn_test);
    tcase_add_test(tc1_1, s21_memchr_test);
    tcase_add_test(tc1_1, s21_memcpy_test);
    tcase_add_test(tc1_1, s21_memmove_test);
    tcase_add_test(tc1_1, s21_memset_test);
    tcase_add_test(tc1_1, s21_to_upper_test);
    tcase_add_test(tc1_1, s21_to_lower_test);
    tcase_add_test(tc1_1, s21_to_insert_test);
    tcase_add_test(tc1_1, s21_sprintf_test);
    // tcase_add_test(tc1_1, s21_to_trim_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
